name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'oops, We think this can be better'
        stale-pr-message: 'New addition / improvements'
        stale-issue-label: 'Issue'
        stale-pr-label: 'PR'
